module.exports = {
    sessions: require("./sessions"),
    games: require("./games"),
    genres: require("./genres"),
    radio: require("./radio"),
    art: require("./art"),
    chats: require("./chats"),
    pro: require("./pro"),
    users: require("./users"),
    admin: require("./admin"),
    orders: require("./orders"),
    news: require("./news"),
    site: require("./site"),
    sitemap: require("./sitemap"),
};
